// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDruyrNvp_pFGpA4xwi5F367F7LNzul6Cw',
    appId: '1:965822076914:web:81505b8c2853ce54fc7d6b',
    messagingSenderId: '965822076914',
    projectId: 'chatapp-db3c1',
    authDomain: 'chatapp-db3c1.firebaseapp.com',
    storageBucket: 'chatapp-db3c1.appspot.com',
    measurementId: 'G-7KQKF0X149',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAvJzhhO_QUQOUzJUWgxj9Z1hd8jZ4iKY',
    appId: '1:965822076914:android:7bf5b1599161cffcfc7d6b',
    messagingSenderId: '965822076914',
    projectId: 'chatapp-db3c1',
    storageBucket: 'chatapp-db3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIWJz8js_euU_bJTx5te8noC8RGh5u0gE',
    appId: '1:965822076914:ios:e0e6ac6da49deef4fc7d6b',
    messagingSenderId: '965822076914',
    projectId: 'chatapp-db3c1',
    storageBucket: 'chatapp-db3c1.appspot.com',
    iosClientId: '965822076914-is192o1fkbetff03emmj4q3isoqkfdbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
